# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
     - master
 paths:
  include:
    - dotnet/aspnet/webappOnLinux/*

pool:
  vmImage: 'ubuntu-16.04'




variables:
  solution:  'dotnet/aspnet/webappOnLinux/Application/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: NuGetToolInstaller@1
 

 
- task: UseDotNet@2
  inputs:
    version: '2.2.x'
    packageType: runtime


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
